language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 5.5
        - php: 5.6
        - php: 7.0

install:
    - composer install --prefer-dist --dev

script:
   - vendor/bin/phpspec run
