build:
	docker build -t rest-api-base .
	docker build -t rest-api-nginx nginx/
	docker build -t rest-api-php:5.5 php55/
	docker build -t rest-api-php:5.6 php56/
	docker build -t rest-api-tunnel tunneling/